from io import BytesIO
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn


def _get_pdf_styles():
    """Get styled PDF paragraph styles."""
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle', parent=styles['Heading1'],
        fontSize=24, textColor=colors.HexColor('#1e1b4b'),
        spaceAfter=4, alignment=TA_CENTER, fontName='Helvetica-Bold'
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle', parent=styles['Normal'],
        fontSize=10, textColor=colors.HexColor('#64748b'),
        spaceAfter=20, alignment=TA_CENTER
    )
    heading_style = ParagraphStyle(
        'SectionHeading', parent=styles['Heading2'],
        fontSize=13, textColor=colors.HexColor('#4F46E5'),
        spaceAfter=8, spaceBefore=18, fontName='Helvetica-Bold',
        borderPadding=(0, 0, 4, 0)
    )
    body_style = ParagraphStyle(
        'BodyText', parent=styles['Normal'],
        fontSize=10.5, leading=16, textColor=colors.HexColor('#1e293b'),
        alignment=TA_JUSTIFY, spaceAfter=6
    )
    bullet_style = ParagraphStyle(
        'BulletText', parent=body_style,
        leftIndent=20, bulletIndent=8, spaceAfter=4
    )
    bold_item_style = ParagraphStyle(
        'BoldItem', parent=body_style,
        spaceAfter=2, spaceBefore=8
    )
    sub_text_style = ParagraphStyle(
        'SubText', parent=body_style,
        leftIndent=12, fontSize=10, textColor=colors.HexColor('#475569'),
        spaceAfter=4
    )
    label_style = ParagraphStyle(
        'LabelText', parent=body_style,
        fontSize=9, textColor=colors.HexColor('#7c3aed'), fontName='Helvetica-Bold',
        spaceAfter=2, spaceBefore=12
    )

    return {
        'title': title_style,
        'subtitle': subtitle_style,
        'heading': heading_style,
        'body': body_style,
        'bullet': bullet_style,
        'bold_item': bold_item_style,
        'sub_text': sub_text_style,
        'label': label_style,
    }


def _add_divider(story):
    """Add a thin horizontal divider."""
    story.append(Spacer(1, 0.08 * inch))
    story.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor('#e2e8f0'), spaceAfter=8, spaceBefore=4
    ))


def generate_pdf(content: Dict[str, Any], doc_type: str) -> BytesIO:
    """Generate a styled PDF document from generation content."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        rightMargin=60, leftMargin=60, topMargin=50, bottomMargin=40
    )

    s = _get_pdf_styles()
    story = []

    if doc_type == "resume":
        story.append(Paragraph("Professional Resume", s['title']))
        story.append(Paragraph("Generated by SkillPilot", s['subtitle']))
        _add_divider(story)

        if content.get('summary'):
            story.append(Paragraph("Professional Summary", s['heading']))
            story.append(Paragraph(str(content['summary']), s['body']))

        if content.get('skills'):
            story.append(Paragraph("Skills", s['heading']))
            skills_text = " &bull; ".join(content['skills'])
            story.append(Paragraph(skills_text, s['body']))

        if content.get('experience'):
            story.append(Paragraph("Experience", s['heading']))
            for exp in content['experience']:
                title_text = f"<b>{exp.get('title', '')}</b> — {exp.get('company', '')}"
                duration = exp.get('duration', '')
                story.append(Paragraph(title_text, s['bold_item']))
                if duration:
                    story.append(Paragraph(f"<i>{duration}</i>", s['sub_text']))
                for point in exp.get('points', []):
                    story.append(Paragraph(f"&bull; {point}", s['bullet']))
                story.append(Spacer(1, 0.06 * inch))

        if content.get('education'):
            story.append(Paragraph("Education", s['heading']))
            for edu in content['education']:
                story.append(Paragraph(
                    f"<b>{edu.get('degree', '')}</b> — {edu.get('institution', '')}",
                    s['bold_item']
                ))
                year = edu.get('year', '')
                if year:
                    story.append(Paragraph(f"<i>{year}</i>", s['sub_text']))

        if content.get('projects'):
            story.append(Paragraph("Projects", s['heading']))
            for proj in content['projects']:
                story.append(Paragraph(f"<b>{proj.get('name', '')}</b>", s['bold_item']))
                story.append(Paragraph(str(proj.get('description', '')), s['sub_text']))
                if proj.get('tech'):
                    story.append(Paragraph(
                        f"<font color='#7c3aed'>Tech:</font> {', '.join(proj['tech'])}",
                        s['sub_text']
                    ))
                story.append(Spacer(1, 0.04 * inch))

    elif doc_type == "project":
        story.append(Paragraph("Final Year Project Report", s['title']))
        story.append(Paragraph("Generated by SkillPilot", s['subtitle']))
        _add_divider(story)

        sections = [
            ("Abstract", "abstract"),
            ("Problem Statement", "problem_statement"),
            ("System Architecture", "architecture"),
            ("Implementation", "implementation"),
        ]
        for heading, key in sections:
            if content.get(key):
                story.append(Paragraph(heading, s['heading']))
                story.append(Paragraph(str(content[key]), s['body']))

        if content.get('objectives'):
            story.append(Paragraph("Objectives", s['heading']))
            for i, obj in enumerate(content['objectives'], 1):
                story.append(Paragraph(f"{i}. {obj}", s['bullet']))

        if content.get('modules'):
            story.append(Paragraph("Modules", s['heading']))
            for mod in content['modules']:
                story.append(Paragraph(
                    f"<b>{mod.get('name', '')}</b>", s['bold_item']
                ))
                story.append(Paragraph(mod.get('description', ''), s['sub_text']))

        if content.get('tech_stack'):
            story.append(Paragraph("Technology Stack", s['heading']))
            for tech in content['tech_stack']:
                if isinstance(tech, dict):
                    story.append(Paragraph(
                        f"&bull; <b>{tech.get('name', '')}</b> — {tech.get('purpose', '')}",
                        s['bullet']
                    ))
                else:
                    story.append(Paragraph(f"&bull; {tech}", s['bullet']))

        if content.get('future_scope'):
            story.append(Paragraph("Future Scope", s['heading']))
            for item in content['future_scope']:
                story.append(Paragraph(f"&bull; {item}", s['bullet']))

        if content.get('viva_questions'):
            story.append(Paragraph("Viva Questions", s['heading']))
            _add_divider(story)
            for i, qa in enumerate(content['viva_questions'], 1):
                if isinstance(qa, dict):
                    story.append(Paragraph(
                        f"<b>Q{i}.</b> {qa.get('question', '')}", s['bold_item']
                    ))
                    story.append(Paragraph(
                        f"<font color='#475569'><b>A:</b> {qa.get('answer', '')}</font>",
                        s['sub_text']
                    ))
                    story.append(Spacer(1, 0.06 * inch))

    elif doc_type == "english":
        story.append(Paragraph("English Improvement", s['title']))
        story.append(Paragraph("Generated by SkillPilot", s['subtitle']))
        _add_divider(story)
        tone_colors = {
            "formal": "#7c3aed",
            "semi_formal": "#2563eb",
            "simple": "#059669",
        }
        for tone, label in [("formal", "Formal"), ("semi_formal", "Semi-Formal"), ("simple", "Simple")]:
            if content.get(tone):
                color = tone_colors.get(tone, '#4F46E5')
                tone_heading = ParagraphStyle(
                    f'Tone_{tone}', parent=s['heading'],
                    textColor=colors.HexColor(color)
                )
                story.append(Paragraph(label, tone_heading))
                story.append(Paragraph(str(content[tone]), s['body']))
                story.append(Spacer(1, 0.1 * inch))

    elif doc_type == "interview":
        story.append(Paragraph("Interview Preparation", s['title']))
        story.append(Paragraph("Generated by SkillPilot", s['subtitle']))
        _add_divider(story)
        if content.get('answer'):
            story.append(Paragraph("Suggested Answer", s['heading']))
            story.append(Paragraph(str(content['answer']), s['body']))
        if content.get('delivery_notes'):
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph("Delivery Notes", s['label']))
            story.append(Paragraph(str(content['delivery_notes']), s['sub_text']))

    doc.build(story)
    buffer.seek(0)
    return buffer


def _add_docx_divider(doc):
    """Add a thin horizontal line to DOCX."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(4)
    p.paragraph_format.space_after = Pt(8)
    pPr = p._p.get_or_add_pPr()
    pBdr = pPr.makeelement(qn('w:pBdr'), {})
    bottom = pBdr.makeelement(qn('w:bottom'), {
        qn('w:val'): 'single',
        qn('w:sz'): '4',
        qn('w:space'): '1',
        qn('w:color'): 'CBD5E1',
    })
    pBdr.append(bottom)
    pPr.append(pBdr)


def _style_docx_heading(heading, color_hex='4F46E5'):
    """Apply color to a docx heading."""
    for run in heading.runs:
        run.font.color.rgb = RGBColor.from_string(color_hex)


def generate_docx(content: Dict[str, Any], doc_type: str) -> BytesIO:
    """Generate a styled DOCX document from generation content."""
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # Set narrow margins
    for section in doc.sections:
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(1.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    if doc_type == "resume":
        title = doc.add_heading('Professional Resume', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _style_docx_heading(title, '1E1B4B')

        sub = doc.add_paragraph('Generated by SkillPilot')
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.size = Pt(9)
        sub.runs[0].font.color.rgb = RGBColor.from_string('94A3B8')
        _add_docx_divider(doc)

        if content.get('summary'):
            h = doc.add_heading('Professional Summary', level=1)
            _style_docx_heading(h)
            doc.add_paragraph(str(content['summary']))

        if content.get('skills'):
            h = doc.add_heading('Skills', level=1)
            _style_docx_heading(h)
            doc.add_paragraph(' | '.join(content['skills']))

        if content.get('experience'):
            h = doc.add_heading('Experience', level=1)
            _style_docx_heading(h)
            for exp in content['experience']:
                p = doc.add_paragraph()
                run = p.add_run(f"{exp.get('title', '')} — {exp.get('company', '')}")
                run.bold = True
                run.font.size = Pt(11)
                duration = exp.get('duration', '')
                if duration:
                    dur_p = doc.add_paragraph()
                    dur_run = dur_p.add_run(duration)
                    dur_run.italic = True
                    dur_run.font.size = Pt(9.5)
                    dur_run.font.color.rgb = RGBColor.from_string('64748B')
                for point in exp.get('points', []):
                    doc.add_paragraph(point, style='List Bullet')

        if content.get('education'):
            h = doc.add_heading('Education', level=1)
            _style_docx_heading(h)
            for edu in content['education']:
                p = doc.add_paragraph()
                run = p.add_run(f"{edu.get('degree', '')} — {edu.get('institution', '')}")
                run.bold = True
                year = edu.get('year', '')
                if year:
                    yr_p = doc.add_paragraph()
                    yr_run = yr_p.add_run(year)
                    yr_run.italic = True
                    yr_run.font.size = Pt(9.5)
                    yr_run.font.color.rgb = RGBColor.from_string('64748B')

        if content.get('projects'):
            h = doc.add_heading('Projects', level=1)
            _style_docx_heading(h)
            for proj in content['projects']:
                p = doc.add_paragraph()
                run = p.add_run(proj.get('name', ''))
                run.bold = True
                doc.add_paragraph(str(proj.get('description', '')))
                if proj.get('tech'):
                    tech_p = doc.add_paragraph()
                    label_run = tech_p.add_run('Tech: ')
                    label_run.bold = True
                    label_run.font.color.rgb = RGBColor.from_string('7C3AED')
                    label_run.font.size = Pt(9.5)
                    tech_run = tech_p.add_run(', '.join(proj['tech']))
                    tech_run.font.size = Pt(9.5)

    elif doc_type == "project":
        title = doc.add_heading('Final Year Project Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _style_docx_heading(title, '1E1B4B')

        sub = doc.add_paragraph('Generated by SkillPilot')
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.size = Pt(9)
        sub.runs[0].font.color.rgb = RGBColor.from_string('94A3B8')
        _add_docx_divider(doc)

        sections = [
            ("Abstract", "abstract"),
            ("Problem Statement", "problem_statement"),
            ("System Architecture", "architecture"),
            ("Implementation", "implementation"),
        ]
        for heading, key in sections:
            if content.get(key):
                h = doc.add_heading(heading, level=1)
                _style_docx_heading(h)
                doc.add_paragraph(str(content[key]))

        if content.get('objectives'):
            h = doc.add_heading('Objectives', level=1)
            _style_docx_heading(h)
            for i, obj in enumerate(content['objectives'], 1):
                doc.add_paragraph(f"{i}. {obj}")

        if content.get('modules'):
            h = doc.add_heading('Modules', level=1)
            _style_docx_heading(h)
            for mod in content['modules']:
                p = doc.add_paragraph()
                run = p.add_run(mod.get('name', ''))
                run.bold = True
                p.add_run(f": {mod.get('description', '')}")

        if content.get('tech_stack'):
            h = doc.add_heading('Technology Stack', level=1)
            _style_docx_heading(h)
            for tech in content['tech_stack']:
                if isinstance(tech, dict):
                    p = doc.add_paragraph(style='List Bullet')
                    run = p.add_run(tech.get('name', ''))
                    run.bold = True
                    p.add_run(f" — {tech.get('purpose', '')}")
                else:
                    doc.add_paragraph(str(tech), style='List Bullet')

        if content.get('future_scope'):
            h = doc.add_heading('Future Scope', level=1)
            _style_docx_heading(h)
            for item in content['future_scope']:
                doc.add_paragraph(item, style='List Bullet')

        if content.get('viva_questions'):
            h = doc.add_heading('Viva Questions', level=1)
            _style_docx_heading(h)
            _add_docx_divider(doc)
            for i, qa in enumerate(content['viva_questions'], 1):
                if isinstance(qa, dict):
                    p = doc.add_paragraph()
                    q_run = p.add_run(f"Q{i}. ")
                    q_run.bold = True
                    p.add_run(qa.get('question', ''))
                    a_p = doc.add_paragraph()
                    a_label = a_p.add_run('A: ')
                    a_label.bold = True
                    a_label.font.color.rgb = RGBColor.from_string('475569')
                    a_text = a_p.add_run(qa.get('answer', ''))
                    a_text.font.color.rgb = RGBColor.from_string('475569')

    elif doc_type == "english":
        title = doc.add_heading('English Improvement', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _style_docx_heading(title, '1E1B4B')

        sub = doc.add_paragraph('Generated by SkillPilot')
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.size = Pt(9)
        sub.runs[0].font.color.rgb = RGBColor.from_string('94A3B8')
        _add_docx_divider(doc)

        tone_colors = {
            "formal": '7C3AED',
            "semi_formal": '2563EB',
            "simple": '059669',
        }
        for tone, label in [("formal", "Formal"), ("semi_formal", "Semi-Formal"), ("simple", "Simple")]:
            if content.get(tone):
                h = doc.add_heading(label, level=1)
                _style_docx_heading(h, tone_colors.get(tone, '4F46E5'))
                doc.add_paragraph(str(content[tone]))

    elif doc_type == "interview":
        title = doc.add_heading('Interview Preparation', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _style_docx_heading(title, '1E1B4B')

        sub = doc.add_paragraph('Generated by SkillPilot')
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.size = Pt(9)
        sub.runs[0].font.color.rgb = RGBColor.from_string('94A3B8')
        _add_docx_divider(doc)

        if content.get('answer'):
            h = doc.add_heading('Suggested Answer', level=1)
            _style_docx_heading(h)
            doc.add_paragraph(str(content['answer']))

        if content.get('delivery_notes'):
            h = doc.add_heading('Delivery Notes', level=2)
            _style_docx_heading(h, '7C3AED')
            p = doc.add_paragraph()
            run = p.add_run(str(content['delivery_notes']))
            run.font.color.rgb = RGBColor.from_string('64748B')
            run.italic = True

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
